---
settings:
  name: ONTAP FLI
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ja-jp,us-en,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: ONTAP FLI のドキュメント
    url: "/index.html"
  - section: san-migration
  - title: 法的通知
    url: "/reference_legal_notices.html"
homepage:
  tiles:
  - title: FLI のワークフロー
    links:
    - title: オフラインワークフロー
      url: "/san-migration/concept_fli_offline_workflow.html"
    - title: オンラインワークフロー
      url: "/san-migration/concept_fli_online_workflow.html"
    - title: FLI の 7-Mode から ONTAP への移行ワークフロー
      url: "/san-migration/concept_fli_7_mode_to_ontap_transition_workflow.html"
    - title: FLI での Workflow Automation （ WFA ）の使用
      url: "/san-migration/concept_fli_using_workflow_automation_wfa.html"
product-family:
  name: ONTAP
  repo: ontap-family
  sidebar_label: すべてのONTAP 製品ドキュメント
