---
permalink: phases/plan-prepare-phase.html 
sidebar: sidebar 
keywords: plan and prepare phase, foreign lun import, fli, migration planning, test migration, cutover, intercluster lif, iscsi fli, gap analysis, san migration, fc fli, zoning, test migration 
summary: 1 つ以上のテスト移行を実行して、アレイ、ネットワーク、ファブリック、ONTAP 構成とホスト修復手順が正しいことを確認し、本番環境のスケジューリングに外挿できるスループットサンプルを収集します。 
---
= ONTAP外部LUNインポート（FLI）テスト移行およびカットオーバー計画
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
1 つ以上のテスト移行を実行して、アレイ、ネットワーク、ファブリック、ONTAP 構成とホスト修復手順が正しいことを確認し、本番環境のスケジューリングに外挿できるスループットサンプルを収集します。

優れたテスト移行では、以下の点が検証されます：

* バックエンドの準備状況：IC LIFへの到達可能性、iSCSIセッションの安定性、および外部LUNの検出が、すべてのパスで一貫していること。
* ワークフローの正確性：インポート関係の作成/開始/表示/完了（およびオプションの検証）は、選択されたモード（オンライン/オフライン）で期待どおりに動作します。
* ホストの準備状況：ホストの再スキャン/修復手順が、対象となるユースケース（ESXi VMFS/RDM、Windowsスタンドアロン/WFCなど）で確実に機能すること。
* 運用上の見積もり：テスト実行で観測されたスループットは、本番環境への移行期間を見積もるための最も現実的な根拠となり、一般的にあらゆる一般的なベンチマークよりも優れています。




[[test-migration-example-using-hitachi-ams2100]]
== Hitachi AMS2100 を使用したテスト移行の例

Hitachi AMS2100 を外部アレイとして使用したテスト移行の例を次に示します。実行するアレイ、ホストオペレーティングシステム、およびその他の変数によっては、手順が異なる場合があります。

テスト移行を実行するために必要な手順の一般的なガイドとして、以下の例を使用できます。テストによって明らかになった問題を解決するための時間を十分に確保できるように、できるだけ早い段階でテスト移行を実行することを推奨します。本番移行に進む前に、ソースアレイとデスティネーションアレイのすべての組み合わせについてテスト移行を実行する必要があります。

.手順
. ソースアレイに 2GB のテスト用 LUN を作成します。
+
.. Hitachi Storage Navigator Modularに `system`としてログインします。
.. *AMS 2100 array*を選択してください。
.. * Show and Configure Array* をクリックします。
..  `root`を使用してログインします。
.. [* グループ ] を展開し、 [* 論理ユニット ] を選択します。
.. 「 * Create LU * 」を選択して、テスト LUN を作成します。
.. 2GB のテスト用 LUN を作成します。
.. [OK] をクリックします。
.. ここで LUN の割り当てを省略し、 * Close * をクリックして続行します。
.. テスト用LUNが作成されたことを確認します。


. テストLUNを、ONTAPイニシエータ用に作成したホストグループに割り当てます。
+
.. [* グループ ] を展開し、 [* 論理ユニット ] を選択します。
.. テストLUNを*cDOT_FLI*ホストグループにマッピングするには、*Host Groups*を選択します。
.. 前の手順で作成したホストグループ *cDOT_FLI* を選択し、*Edit Host Group* をクリックします。
.. ホストグループに使用するポートを選択してください。この例では、*0a*、*0e*、*1a*、*1e*を選択します。*Forced Set to All Selected Ports*オプションを選択してください。
.. HDS Storage Navigatorで、ホストグループを編集します。
.. *論理ユニット*をクリックして、テスト用のLUNを追加します。
.. OK * をクリックして LUN をマッピングします。
.. [ はい、上記の警告を読んでホストグループを編集する ] を選択し、 [ * 確認 * ] をクリックします。
.. ホストグループが作成されたことを確認し、 * 閉じる * をクリックします。


. テスト用 LUN とソースストレージからデスティネーションストレージへのマッピングを確認し、 Foreign LUN Import （ FLI ）を実行します。
+
..  `admin`ユーザーを使用して、SSH経由でONTAPストレージにログインします。
.. モードを*Advanced*に変更します。
+
DataMig-cmode::> set -privilege advanced

.. 高度なコマンドを続行するかどうかを尋ねられたら、「y」と入力します。
.. ONTAP上のソース アレイを検出します。数分待ってから、ソース アレイの検出を再試行します。
+
storage array show

+
ストレージアレイが初めて検出されたとき、 ONTAP の自動検出でアレイが表示されないことがあります。次の手順に従って、 ONTAP イニシエータポートが接続されているスイッチポートをリセットします。

+
たとえば、DataMig-cmodeクラスタイニシエータポート `0a`および `0b`のONTAPは、Ciscoポート `4/9`および `4/11`に接続されています。Ciscoスイッチのポート `4/9`をリセットするには：

+
[listing]
----
conf t
interface fc4/
shutdown
no shutdown
exit
exit
----
+
通常、 1 つのポートをリセットするだけで十分です。1 つのポートをリセットしたら、アレイリストと LUN パスを確認します。

.. ソースアレイがすべてのイニシエータポートを通じて検出されていることを確認してください。
+
storage array config show -array-name HITACHI_DF600F_1

+
[listing]
----
             LUN   LUN
Node         Group Count     Array Name       Array Target Port Initiator
------------ ----- ----- ---------------------------- -----------------------
DataMig-cmode-01 0     1    HITACHI_DF600F_1     50060e801046b960        0a
                                                 50060e801046b964        0b
                                                 50060e801046b968        0a
                                                 50060e801046b96c        0b
DataMig-cmode-02 0     1    HITACHI_DF600F_1     50060e801046b960        0a
                                                 50060e801046b964        0b
                                                 50060e801046b968        0a
                                                 50060e801046b96c        0b
----
.. HitachiストレージからマッピングされたテストLUNを一覧表示し、ディスクのプロパティとパスを確認します。
+
storage disk show -array-name HITACHI_DF600F_1 -instance

+
[listing]
----

                  Disk: HIT-1.1
        Container Type: unassigned
            Owner/Home: -  / -
               DR Home: -
    Stack ID/Shelf/Bay: -  / -  / -
                   LUN: 0
                 Array: HITACHI_DF600F_1
                Vendor: HITACHI
                 Model: DF600F
         Serial Number: 83017542001A
                   UID: 48495441:43484920:38333031:37353432:30303236:00000000:00000000:00000000:00000000:00000000
                   BPS: 512
         Physical Size: -
              Position: present
Checksum Compatibility: block
             Aggregate: -
                  Plex: -
Paths:
                                LUN  Initiator Side        Target Side                                            Link
Controller         Initiator     ID  Switch Port           Switch Port           Acc Use  Target Port     TPGN    Speed  I/O KB/s  IOPS
------------------ ---------  -----  --------------------  --------------------  --- ---  --------------  ------  ----   --- -----
DataMig-cmode-01   0a             0  DM-Cisco9506-1:4-9    DM-Cisco9506-1:2-24   AO  INU  50060e801046b968  2   2 Gb/S    0  0
DataMig-cmode-01   0b             0  DM-Cisco9506-2:4-9    DM-Cisco9506-2:2-24   AO  INU  50060e801046b96c  2   2 Gb/S    0  0
DataMig-cmode-01   0b             0  DM-Cisco9506-2:4-9    DM-Cisco9506-2:1-14   AO  INU  50060e801046b964  1   2 Gb/S    0  0
DataMig-cmode-01   0a             0  DM-Cisco9506-1:4-9    DM-Cisco9506-1:1-14   AO  INU  50060e801046b960  1   2 Gb/S    0  0
DataMig-cmode-02   0a             0  DM-Cisco9506-1:4-11   DM-Cisco9506-1:2-24   AO  INU  50060e801046b968  2   2 Gb/S    0  0
DataMig-cmode-02   0b             0  DM-Cisco9506-2:4-11   DM-Cisco9506-2:2-24   AO  INU  50060e801046b96c  2   2 Gb/S    0  0
DataMig-cmode-02   0b             0  DM-Cisco9506-2:4-11   DM-Cisco9506-2:1-14   AO  INU  50060e801046b964  1   2 Gb/S    0  0
DataMig-cmode-02   0a             0  DM-Cisco9506-1:4-11   DM-Cisco9506-1:1-14   AO  INU  50060e801046b960  1   2 Gb/S    0  0

Errors:
-

DataMig-cmode::*>
----


. シリアル番号を使用して、ソースLUNを外部LUNとしてマークします：
+
storage disk set-foreign-lun { -serial-number 83017542001A } -is-foreign true

+
.. ソースLUNが外部LUNとしてマークされていることを確認します。
+
storage disk show -array-name HITACHI_DF600F_1

.. すべての外部アレイとそのシリアル番号を一覧表示します：
+
storage disk show -container-type foreign -fields serial-number

+

NOTE: lun create コマンドは、パーティションオフセットに基づいてサイズとアライメントを検出し、 foreign-disk 引数に従って LUN を作成します。



. デスティネーション ボリュームを作成します：
+
vol create -vserver datamig flivol aggr1 -size 10g

. 外部LUNを使用してテストLUNを作成します。
+
lun create -vserver datamig -path /vol/flivol/testlun1 -ostype linux -foreign-disk 83017542001A

+
.. テストLUNを一覧表示し、ソースLUNと比較してLUNのサイズを確認します。
+
lun show

+

NOTE: FLI オフライン移行の場合は、 LUN をオンラインにして igroup にマッピングしてから、オフラインにして LUN インポート関係を作成する必要があります。



. イニシエータを追加せずに、FCPプロトコルのテストigroupを作成します：
+
lun igroup create -vserver datamig -igroup testig1 -protocol fcp -ostype linux

. テストLUNをテストigroupにマッピングします：
+
lun map -vserver datamig -path /vol/flivol/testlun1 -igroup testig1

. テストLUNをオフラインにする：
+
lun offline -vserver datamig -path /vol/flivol/testlun1

. テストLUNと外部LUNとの間でインポート関係を作成します：
+
lun import create -vserver datamig -path /vol/flivol/testlun1 -foreign-disk 83017542001A

. 移行（インポート）を開始します：
+
lun import start -vserver datamig -path /vol/flivol/testlun1

+
.. インポートの進捗状況を監視する：
+
lun import show -vserver datamig -path /vol/flivol/testlun1

.. インポートジョブが正常に完了したことを確認します。
+
lun import show -vserver datamig -path /vol/flivol/testlun1

+
[listing]
----
vserver foreign-disk   path                operation admin operational percent
                                         in progress state state       complete
-------------------------------------------------------------------------------
datamig 83017542001A   /vol/flivol/testlun1
                                           import    started
                                                           completed     100
----


. ソースLUNと宛先LUNを比較するための検証ジョブを開始します。検証の進捗状況を監視する：
+
lun import verify start -vserver datamig -path /vol/flivol/testlun1

+
[listing]
----
DataMig-cmode::*> lun import show -vserver datamig -path /vol/flivol/testlun1
vserver foreign-disk   path                operation admin operational percent
                                         in progress state state       complete
-------------------------------------------------------------------------------
datamig 83017542001A   /vol/flivol/testlun1
                                           verify    started
                                                           in_progress     44
----
+
.. 検証ジョブがエラーなく完了したことを確認してください。
+
lun import show -vserver datamig -path /vol/flivol/testlun1

+
[listing]
----
vserver foreign-disk   path                operation admin operational percent
                                         in progress state state       complete
-------------------------------------------------------------------------------
datamig 83017542001A   /vol/flivol/testlun1
                                           verify    started
                                                           completed      100
----


. 移行ジョブを削除するには、インポート関係を削除します。
+
lun import delete -vserver datamig -path /vol/flivol/testlun1

+
lun import show -vserver datamig -path /vol/flivol/testlun1

. テストLUNをテストigroupからアンマップします：
+
lun unmap -vserver datamig -path /vol/flivol/testlun1 -igroup testig1

. テストLUNをオンラインにします：
+
lun online -vserver datamig -path /vol/flivol/testlun1

. 外部LUN属性をfalseに設定する：
+
storage disk modify -serial-number 83017542001A -is-foreign false

+

NOTE: ONTAP イニシエータポートがあるソースストレージに作成されたホストグループは削除しないでください。同じホストグループが、そのソースアレイからの移行時に再利用されます。

. ソースストレージからテスト用 LUN を削除します。
+
.. Hitachi Storage Navigator Modular にシステムとしてログインします。
.. *AMS 2100 array*を選択し、*Show and Configure Array*をクリックします。
..  `root`を使用してログインします。
.. [*Groups] を選択し、 [*Host Groups] を選択します。
.. *cDOT_FLI Igroup*を選択し、*ホストグループの編集*をクリックします。
.. 「ホストグループの編集」ウィンドウで、テストLUNをマッピングするために選択したすべてのターゲットポートを選択し、*選択したすべてのポートに強制設定*を選択します。
.. 論理ユニット * タブを選択します。
.. [*Assigned Logical Units*] ウィンドウからテスト LUN を選択します。
.. 「 * Remove * 」を選択して LUN マッピングを削除します。
.. [OK] をクリックします。


. ホストグループは削除せずに、テスト用 LUN の削除を続行します。
+
.. *論理単位*を選択します。
.. 前の手順で作成したテスト用LUNを選択します。
.. ［ * LUN の削除 * ］ をクリックします。
.. [* Confirm * （確認） ] をクリックして、テスト LUN を削除します。


. デスティネーションストレージ上のテスト用 LUN を削除します。
+
..  `admin`ユーザーを使用して SSH 経由で ONTAP ストレージにログインします。
.. NetApp ストレージシステムでテスト LUN をオフラインにします。
+
lun offline -vserver datamig -path /vol/flivol/testlun1

+

NOTE: 別のホスト LUN を選択しないように注意してください。

.. NetApp ストレージシステムのテスト LUN を破棄します：
+
lun destroy -vserver datamig -path /vol/flivol/testlun1

.. NetApp ストレージシステムでテストボリュームをオフラインにします。
+
vol offline -vserver datamig -volume flivol

.. NetApp ストレージシステムのテストボリュームを破棄します：
+
vol destroy -vserver datamig -volume flivol




