---
permalink: san-migration/reference_site_survey_and_planning_worksheet_questionnaire_tab.html 
sidebar: sidebar 
keywords: site, survey and planning worksheet, questionnaire tab 
summary: Site Survey and Planning ワークシートの一部として、移行に関する最初のアンケートの移行プロジェクト情報を含むタブを設定する必要があります。 
---
= Site Survey and Planning ワークシートのアンケートタブ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Site Survey and Planning ワークシートの一部として、移行に関する最初のアンケートの移行プロジェクト情報を含むタブを設定する必要があります。

次の例は、アンケートタブの設定方法を示しています。

|===
3+| 移行プロジェクト情報 


 a| 
プロジェクトタイプ（ Project Type ）
 a| 
☐データ移行

☐その他
 a| 



 a| 
データ移行の目的
 a| 
&#9; 目的 &#9;
 a| 



 a| 
ソースデバイス
 a| 
ストレージ： [ ストレージタイプ ]

いいえ数： [ いいえ数 ]

シンプロビジョニング：☐はい☐いいえ
 a| 
すべてのデバイスを列挙します



 a| 
クライアントデバイス
 a| 
オペレーティングシステム： [OS バージョン ]

SAN ブート：☐はい☐いいえ

MPIO ： [MPIO バージョン ]

HBA ： [HBA ベンダー、モデル、ファームウェア ]
 a| 



 a| 
ファブリックスイッチ
 a| 
ベンダー：

モデル：

ファームウェア：

いいえ数：
 a| 



 a| 
現在のプロトコル
 a| 
☐ FCP

☐ iSCSI
 a| 



 a| 
Volume Manager の略
 a| 
ベンダー：

製品：

バージョン：
 a| 



 a| 
デスティネーションデバイス（ストレージ）
 a| 
ストレージ： [ ストレージ ]

いいえ[ 数値 ]

シンプロビジョニング：☐はい☐いいえ
 a| 
このサービスではネットアップストレージコントローラのみを使用します



 a| 
移行するデータの量（ TB 単位）
 a| 
&#9; データ量 &#9;93
 a| 
概要と詳細（各ソースデバイス）



 a| 
LUN の数
 a| 
&#9;LUN 数 &#9;93
 a| 
概要と詳細（各ソースデバイス）



 a| 
データの再構成
 a| 
☐はい☐いいえ
 a| 
お客様は、移行の一環としてボリューム / ディレクトリ / フォルダ / ファイルを異なるデータ構造に移動することを希望していますか？



 a| 
許容される停止範囲
 a| 
停止期間

☐定義済み☐柔軟に対応

標準のメンテナンス時間ポリシー： [ 情報 ]
 a| 
利用可能なシステム停止の回数と期間。メンテナンス時間がある場合は記入してください。



 a| 
完了までの希望時間
 a| 
&#9; 完了までの希望時間 &#9;&#9; 時間の重要度 &#9;
 a| 



 a| 
その他の関連情報
 a| 
&#9;Other Relevant Information （その他の関連情報） &#9;
 a| 



 a| 
お客様の組織名と場所（都道府県および市区町村）
 a| 
 a| 

|===