---
permalink: san-migration/concept_using_fli_to_import_luns_into_all_flash.html 
sidebar: sidebar 
keywords: use, foreign lun import, import luns, aff 
summary: ONTAP は、 FlexArray ソフトウェアのすべてのリリースで AFF をサポートしているわけではありません。それらのリリースでは、 AFF と同じクラスタの AFF 以外のハイアベイラビリティ（ HA ）ペアに Foreign LUN Import （ FLI ）をステージングする必要があります。 
---
= Foreign LUN Import を使用した AFF への LUN のインポート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP は、 FlexArray ソフトウェアのすべてのリリースで AFF をサポートしているわけではありません。それらのリリースでは、 AFF と同じクラスタの AFF 以外のハイアベイラビリティ（ HA ）ペアに Foreign LUN Import （ FLI ）をステージングする必要があります。

ONTAP 9.1 以降では、 AFF で FLI がサポートされます。FKU を使用して、他のアレイから ONTAP クラスタに直接 LUN をインポートできます。

ONTAP 8.3.2 では、 AFF で FLI をサポートするには Process Variance Request （ PVR ）の承認が必要になります。PVR を申請して承認を得る方法については、担当のネットアップアカウントチームにお問い合わせください。承認されると、通常はネットアップのシステムエンジニアである申請者に、 FLI 機能を有効にするための手順が記載された承認書が届きます。

8.3.2 より前のバージョンの ONTAP ソフトウェアでは、一部の書き込み最適化の影響により、 AFF で FlexArray がサポートされていません。AFF を使用している同じクラスタの AFF 以外の HA ペアに FLI インポートをステージングする必要があります。移行が完了したら、 vol や LUN の移動などのノンストップオペレーション（ NDO ）を使用して、移行した LUN を AFF に移動できます。AFF クラスタに AFF 以外のノードがない場合は、アカウントチームに問い合わせて一時貸し出し機が利用可能かどうかを相談してください。
