---
permalink: san-migration/concept_migration_analyze_phase_workflow.html 
sidebar: sidebar 
keywords: analyze, phase, workflow 
summary: 分析フェーズでは、移行計画を立てる前に対処する必要がある項目について調べます。Interoperability Matrix と一致しないホスト構成の仕様を特定する必要があります。 
---
= 分析フェーズのワークフロー
:icons: font
:imagesdir: ../media/


[role="lead"]
分析フェーズでは、移行計画を立てる前に対処する必要がある項目について調べます。Interoperability Matrix と一致しないホスト構成の仕様を特定する必要があります。

ホストごとにターゲット構成（移行後）を特定し、ギャップ分析を実行してサポートされていないコンポーネントを特定します。ホストの分析は、完了後すぐに確認する必要があります。必要な更新には、各ホストで実行されているアプリケーションとの互換性を損なう可能性がある

通常、必要なホストの変更は、実際の移行イベントを開始するまでは行いません。これは、メンテナンス時間のスケジュール設定が一般的に必要になるためですが、システムのパッチの適用や Host Bus Adapter （ HBA ；ホストバスアダプタ）の更新など、可能なかぎり事前にホストを変更することでリスクが低下する場合があります。また、システムの更新は、アプリケーションの更新と連携して同じメンテナンスイベントで頻繁に行われます。通常、移行前に Multipath I/O （ MPIO ；マルチパス I/O ）の構成を変更すると、現在のストレージのサポートにも影響します。たとえば、 Linux でホストから PowerPath を削除してネイティブ MPIO と Asymmetric Logical Unit Access （ ALUA ）を使用するように再構成すると、現在のストレージ構成でサポートされなくなることがあります。

MPIO の再構成を移行後まで遅らせることで、必要に応じてロールバックのプロセスを簡易化できます。

計画フェーズのタスクを次の表に示します。

[cols="2*"]
|===
| コンポーネント | タスク 


 a| 
ホスト
 a| 
. 各ホストのギャップ分析を実行します。NetApp IMT で選択したターゲット構成と一致させるために必要なホットフィックスやパッチ、 OS の更新、 HBA ドライバ、ファームウェアのアップグレードを特定します。また、このホストにインストールする他のネットアップソフトウェア（ SnapDrive ® 、 SnapManager ® ）の要件も考慮する必要があります。
. 各ホストのターゲット構成（移行後）を確認します（ OS 構成、 MPIO 、 HBA の詳細、 Host Utility Kit のバージョン）。
. その他のネットアップ製品の要件（ SnapDrive 、 SnapManager ）を確認


|===
* 関連情報 *

https://mysupport.netapp.com/NOW/products/interoperability["ネットアップの相互運用性"]
