---
permalink: san-migration/concept_fli_zoning_requirements.html 
sidebar: sidebar 
keywords: fli, zoning, requirements 
summary: FLI を使用した標準的な移行シナリオでは、次の 4 つのゾーンが必要です。各ゾーンに特定のポートを含める必要があります。 
---
= FLI のゾーニングの要件
:icons: font
:imagesdir: ../media/


[role="lead"]
FLI を使用した標準的な移行シナリオでは、次の 4 つのゾーンが必要です。各ゾーンに特定のポートを含める必要があります。

* ゾーン 1 ：ソースストレージとデスティネーションストレージ（本番ファブリック A ）
+
ゾーン 1 には、ファブリック A のすべてのノード上のすべてのデスティネーションストレージイニシエータポートとすべてのソースストレージターゲットポートを含める必要がありますゾーンメンバーは次のとおりです。

+
** ONTAP - ノード 1 - 0a
** ONTAP -- Node2 -- 0a
** AMS2100 --Ctrl0 --0a
** AMS2100 --Ctrl1-1a


* ゾーン 2 ：ソースストレージとデスティネーションストレージ（本番ファブリック B ）
+
ゾーン 2 には、ファブリック B のすべてのノード上のすべてのデスティネーションストレージのイニシエータポートとすべてのソースストレージのターゲットポートを含める必要がありますゾーン 2 のメンバーは次のとおりです。

+
** ONTAP - Node1 - 0b
** ONTAP -- Node2 -- 0b
** AMS2100 --Ctrl0-0e
** AMS2100 --Ctrl1--1e


* ゾーン 3 ：ホストからデスティネーションストレージ（本番ファブリック A ）
+
ゾーン 3 には、 Host Bus Adapter （ HBA ；ホストバスアダプタ）ポート 1 と本番ファブリック A のデスティネーションのコントローラポートを含める必要がありますゾーン 3 のメンバーは次のとおりです。

+
** ONTAP -- lif1
** ONTAP -- lif3
** ホスト -- HBA0


* ゾーン 4 ：ホストからデスティネーションストレージ（本番ファブリック B ）
+
ゾーン 4 には、 HBA ポート 2 と本番ファブリック B のデスティネーションコントローラポートを含める必要がありますゾーン 4 のメンバーは次のとおりです。

+
** ONTAP -- lif2
** ONTAP -- lif4
** ホスト -- HBA1



