---
permalink: san-migration/concept_fli_7_mode_to_ontap_transition_workflow.html 
sidebar: sidebar 
keywords: fli, 7-mode, ontap, transition, workflow 
summary: ここでは、 FLI の 7-Mode から ONTAP への移行ワークフローの例を示します。移行ワークフローは、オンラインとオフラインのどちらのワークフローとしても実行できます。 
---
= FLI の 7-Mode から ONTAP への移行ワークフロー
:icons: font
:imagesdir: ../media/


[role="lead"]
ここでは、 FLI の 7-Mode から ONTAP への移行ワークフローの例を示します。移行ワークフローは、オンラインとオフラインのどちらのワークフローとしても実行できます。

FLI の移行は、ソース LUN が 32 ビットアグリゲートでホストされている場合や LUN のアライメントが正しくない場合に推奨されます。FLI の 7-Mode から ONTAP への移行では、 7-Mode から ONTAP への LUN の移行と、 LUN アライメントの修正を組み合わせて、 32 ビットアグリゲートから 64 ビットアグリゲートに LUN を移行することができます。7-Mode Transition Tool （ 7MTT ）など、 LUN を移行する他の方法では、 ONTAP に移行する前に、 LUN アライメントの修正や、 32 ビットから 64 ビットへのアグリゲートの変換が必要になる場合があります。

FLI の 7-Mode から ONTAP への移行ワークフローは、オンラインとオフラインのどちらのワークフローでもかまいません。これらのワークフローは、対応するオフラインおよびオンラインの 2 つの FLI 移行ワークフローと機能的には同じですが、ソースアレイが NetApp 7-Mode ストレージアレイである点が異なります。どちらのワークフローでも、対応する移行ワークフローと同じルールと手順を共有します。これには、 FLI オンラインワークフローでサポートされるホストオペレーティングシステムのリストが含まれます。

この例では、 FLI の 7-Mode から ONTAP への移行プロセスの手順をひととおり説明します。FLI の 7-Mode から ONTAP への移行フローには、次のタスクが含まれます。

. ソースアレイとデスティネーションアレイを準備しています
. 停止を伴うカットオーバーの実行
. データをインポートする
. 移行結果の検証
. FLI 移行の移行後のタスク

