---
permalink: san-migration/concept_target_and_initiator_port_zoning.html 
sidebar: sidebar 
keywords: target, initiator, port, zoning 
summary: FLI 移行の実行時は、ソースストレージ LUN にネットアップストレージからアクセスする必要があります。そのためには、ソースストレージのターゲットポートをデスティネーションストレージのイニシエータポートとゾーニングします。 
---
= ターゲットポートとイニシエータポートのゾーニング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FLI 移行の実行時は、ソースストレージ LUN にネットアップストレージからアクセスする必要があります。そのためには、ソースストレージのターゲットポートをデスティネーションストレージのイニシエータポートとゾーニングします。

ソースストレージからホストへの既存のゾーンは変更されず、移行後は非アクティブ化されます。移行された LUN にホストがデスティネーションストレージからアクセスできるように、ホストからデスティネーションストレージへのゾーンが作成されます。

FLI を使用した標準的な移行シナリオでは、次の 4 つのゾーンが必要です。

* ゾーン 1 ：ソースストレージとデスティネーションストレージ（本番ファブリック A ）
* ゾーン 2 ：ソースストレージとデスティネーションストレージ（本番ファブリック B ）
* ゾーン 3 ：ホストからデスティネーションストレージ（本番ファブリック A ）
* ゾーン 4 ：ホストからデスティネーションストレージ（本番ファブリック B ）


ゾーニングに際しては次のベストプラクティスに従ってください。

* ソースストレージのターゲットポートとデスティネーションストレージのターゲットポートを同じゾーンに混在させないでください。
* デスティネーションストレージのイニシエータポートとホストポートを同じゾーンに混在させないでください。
* デスティネーションストレージのターゲットポートとイニシエータポートを同じゾーンに混在させないでください。
* 冗長性を確保するために、各コントローラで少なくとも 2 つのポートでゾーニングします。
* 1 つのイニシエータと 1 つのターゲットでゾーニングすることを推奨し


[NOTE]
====
ソースストレージのターゲットポートをデスティネーションストレージのイニシエータポートとゾーニングすると、 storage array show コマンドを使用して、ソースストレージがデスティネーションストレージで認識されるようになります。ストレージアレイが初めて検出されたとき、ネットアップコントローラがアレイを自動的に表示しないことがあります。これを修正するには、 ONTAP イニシエータポートが接続されているスイッチポートをリセットします。

====