---
permalink: san-migration/concept_target_and_initiator_port_zoning.html 
sidebar: sidebar 
keywords: target, initiator, port, zoning 
summary: FLI 移行の実行時は、ソースストレージ LUN にネットアップストレージからアクセスする必要があります。そのためには、ソースストレージのターゲットポートをデスティネーションストレージのイニシエータポートとゾーニングします。 
---
= ONTAP FLI移行のターゲットおよびイニシエータ ポートのゾーニング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FLI移行では、 NetAppストレージから外部アレイのソースLUNにアクセスできるようにする必要があります。これは、ソースストレージのターゲットポートとNetAppターゲットストレージのイニシエータポートをゾーニングすることで実現されます。

ソースストレージからホストへの既存のゾーンは変更されず、移行後は非アクティブ化されます。移行された LUN にホストがデスティネーションストレージからアクセスできるように、ホストからデスティネーションストレージへのゾーンが作成されます。

FLI を使用した標準的な移行シナリオでは、次の 4 つのゾーンが必要です。

* ゾーン 1 ：ソースストレージとデスティネーションストレージ（本番ファブリック A ）
* ゾーン 2 ：ソースストレージとデスティネーションストレージ（本番ファブリック B ）
* ゾーン 3 ：ホストからデスティネーションストレージ（本番ファブリック A ）
* ゾーン 4 ：ホストからデスティネーションストレージ（本番ファブリック B ）


ゾーニングに際しては次のベストプラクティスに従ってください。

* ソースストレージのターゲットポートとデスティネーションストレージのターゲットポートを同じゾーンに混在させないでください。
* デスティネーションストレージのイニシエータポートとホストポートを同じゾーンに混在させないでください。
* デスティネーションストレージのターゲットポートとイニシエータポートを同じゾーンに混在させないでください。
* 冗長性を確保するために、各コントローラで少なくとも 2 つのポートでゾーニングします。
* 1 つのイニシエータと 1 つのターゲットでゾーニングすることを推奨し


[NOTE]
====
ソースストレージのターゲットポートをデスティネーションストレージのイニシエータポートとゾーニングすると、 storage array show コマンドを使用して、ソースストレージがデスティネーションストレージで認識されるようになります。ストレージアレイが初めて検出されたとき、ネットアップコントローラがアレイを自動的に表示しないことがあります。これを修正するには、 ONTAP イニシエータポートが接続されているスイッチポートをリセットします。

====
FLI を使用した標準的な移行シナリオでは、次の 4 つのゾーンが必要です。各ゾーンに特定のポートを含める必要があります。

* ゾーン 1 ：ソースストレージとデスティネーションストレージ（本番ファブリック A ）
+
ゾーン 1 には、ファブリック A のすべてのノード上のすべてのデスティネーションストレージイニシエータポートとすべてのソースストレージターゲットポートを含める必要がありますゾーンメンバーは次のとおりです。

+
** ONTAP - ノード 1 - 0a
** ONTAP -- Node2 -- 0a
** AMS2100 --Ctrl0 --0a
** AMS2100 --Ctrl1-1a


* ゾーン 2 ：ソースストレージとデスティネーションストレージ（本番ファブリック B ）
+
ゾーン 2 には、ファブリック B のすべてのノード上のすべてのデスティネーションストレージのイニシエータポートとすべてのソースストレージのターゲットポートを含める必要がありますゾーン 2 のメンバーは次のとおりです。

+
** ONTAP - Node1 - 0b
** ONTAP -- Node2 -- 0b
** AMS2100 --Ctrl0-0e
** AMS2100 --Ctrl1--1e


* ゾーン 3 ：ホストからデスティネーションストレージ（本番ファブリック A ）
+
ゾーン 3 には、 Host Bus Adapter （ HBA ；ホストバスアダプタ）ポート 1 と本番ファブリック A のデスティネーションのコントローラポートを含める必要がありますゾーン 3 のメンバーは次のとおりです。

+
** ONTAP -- lif1
** ONTAP -- lif3
** ホスト -- HBA0


* ゾーン 4 ：ホストからデスティネーションストレージ（本番ファブリック B ）
+
ゾーン 4 には、 HBA ポート 2 と本番ファブリック B のデスティネーションコントローラポートを含める必要がありますゾーン 4 のメンバーは次のとおりです。

+
** ONTAP -- lif2
** ONTAP -- lif4
** ホスト -- HBA1



