---
permalink: san-migration/concept_migration_types_supported_by_foreign_lun_import.html 
sidebar: sidebar 
keywords: migration, types, supported, foreign, lun, import 
summary: FLI では、オンライン、オフライン、移行、自動の 4 種類の移行ワークフローがサポートされています。使用するワークフローは、構成やその他の要因によって異なります。 
---
= Foreign LUN Import でサポートされる移行の種類
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FLI では、オンライン、オフライン、移行、自動の 4 種類の移行ワークフローがサポートされています。使用するワークフローは、構成やその他の要因によって異なります。

* オンライン移行では、移行中もクライアントシステムをオンラインのまま維持して他社製アレイからの FLI を実行します（ Windows 、 Linux 、または ESXi ホストオペレーティングシステムが必要です）。
* オフライン移行では、クライアントシステムをオフラインにして他社製アレイからの FLI を実行します。クライアントシステムは新しい LUN にデータをコピーしてから、オンラインに戻します。
* 移行ワークフローでは、 FLI で ONTAP 7-Mode から ONTAP に移行します。これは、ソースアレイが ONTAP であることを除いて、機能的には同じプロセスです。移行ワークフローは、オンラインモードまたはオフラインモードのいずれかで使用できます。
* 自動移行では、 FLI による移行プロセスの一部を Workflow Automation （ WFA ）ソフトウェアを使用して自動化します。WFA を使用した FLI は、オンラインモードまたはオフラインモードのいずれかで使用できます。


アーキテクチャの点では、 4 つの移行ワークフローはとてもよく似ています。いずれのワークフローでも、ネットアップの FlexArray テクノロジを利用して、 ONTAP コントローラをソースアレイの前に配置したイニシエータとして機能させ、この位置を利用して、 LUN をブロック単位でソースからデスティネーション ONTAP アレイ上の LUN にコピーします。

各ワークフローの違いは、カットオーバーが発生する状況、中断時間の長さ、自動化の使用、ソースアレイが ONTAP 7-Mode を実行しているネットアップアレイか他社製アレイかにあります。
