---
permalink: san-migration/map-source-lun-to-destination-online-migration.html 
sidebar: sidebar 
keywords: fli online, perform, disruptive, cutover 
summary: この例では、 FLI オンライン移行プロセスの停止を伴うカットオーバーを実行する一般的な手順を示します。 
---
= FLIオンライン移行のためにソースLUNをONTAPアレイにマッピングする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
外部アレイLUNからデータをインポートするには、まず外部アレイ上でLUNのマッピングを解除し、 ONTAPストレージシステムに再マッピングする必要があります。外部アレイ上のLUNのマッピングを解除するコマンドは、アレイベンダーによって異なります。全体的なプロセスについては、提供されている手順に従い、具体的なコマンドについては、外部アレイのドキュメントを参照してください。

.作業を開始する前に
igroupからホスト（イニシエータ）を削除すると、そのigroupにマッピングされているすべてのLUNに影響します。外部アレイ上の他のLUNへの影響を防ぐため、移行するLUNは、そのigroupにマッピングされている唯一のLUNである必要があります。igroupを共有している他のLUNがある場合は、それらを別のigroupに再マッピングするか、移行するLUN専用の新しいigroupを作成してください。適切なコマンドについては、ベンダーのドキュメントを参照してください。

.手順
. 外部アレイで、ソース LUN がマッピングされているストレージグループを表示します。
+
該当するコマンドについては、ベンダーのドキュメントを参照してください。

. インポートするLUNがESXiホスト用の場合は、以下の手順を確認して従ってください。 link:reference_esxi_caw_ats_remediation.html["ESXi CAW / ATS の修正"] 。
. ホストからソース LUN のマッピングを解除します。
+
[NOTE]
====
中断は 'unmap コマンドを実行した直後に始まります通常、中断時間は分単位です。中断時間は、新しいネットアップターゲットでホストを再ポイントし、 LUN をスキャンするための時間です。

====
. ホストイニシエータが存在しないことを確認します。
. ONTAP クラスタで、デスティネーション LUN をオンラインにし、マッピングされていることを確認します。
+
[source, cli]
----
lun online -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
. LUN がオンラインであることを確認します。
+
[source, cli]
----
lun show -vserver <SVM_name>
----
. ホストのディスクを再スキャンし、 ONTAP ターゲットの LUN を探して、 DSM で LUN が要求されていることを確認します。
+
[NOTE]
====
中断時間はここまでです。

====
. 想定されるすべてのパスが表示されることを確認し、イベントログでエラーがないことを確認します。


.結果
分析および計画フェーズで特定された、中断を伴う未処理のホスト修復タスクがない限り、この移行の中断部分は完了しています。

LUN がオンラインでマッピングされた状態になり、ホストで新しい ONTAP ホスト LUN がマウントされます。読み取りは ONTAP アレイを介してソース LUN に渡され、書き込みは新しい ONTAP ホスト LUN と元のソース LUN の両方に書き込まれます。ソース LUN とデスティネーション LUN は、移行が完了して LUN 関係が解除されるまで同期されたままになります。

.次の手順
link:task_fli_online_importing_the_data.html["外部LUNからデータをインポートする"] 。
