---
permalink: san-migration/reference_clearing_scsi_3_persistent_reservations.html 
sidebar: sidebar 
keywords: clear, scsi-3, persistent, reservations 
summary: Windows クラスタの場合、すべてのクラスタホストがオフラインであっても、クォーラムディスクに対する SCSI-3 の予約を削除する必要があります。 
---
= SCSI-3 の永続的予約をクリアしています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows クラスタの場合、すべてのクラスタホストがオフラインであっても、クォーラムディスクに対する SCSI-3 の予約を削除する必要があります。

ソース LUN に外部ディスクとしてラベル付けしようとすると、次のエラーメッセージが表示されます。

 Error: command failed: The specified foreign disk has SCSI persistent reservations. Disk serial number: "6006016021402700787BAC217B44E411". Clear the reservation using the "storage disk remove-reservation" command before creating the import relationship.
「 storage disk remove-reservation 」コマンドを使用すると、ネットアップコントローラでクォーラムディスクに対する SCSI-3 の予約を削除できます。

[listing]
----
storage disk remove-reservation –disk disk_name
----
このエラーとその修正方法を次に示します。

[listing]
----
cluster-4b::*> lun offline -vserver fli_cluster -path /vol/fli_volume/cluster_1
cluster-4b::*> lun import create -vserver fli_cluster -path /vol/fli_volume/cluster_1 -foreign-disk 6006016021402700787BAC217B44E411
Error: command failed: The specified foreign disk is not marked as foreign. Disk serial number: "6006016021402700787BAC217B44E411".

cluster-4b::*> sto disk show -disk DGC-1.6 -fields serial-number,is-foreign
 (storage disk show)
disk is-foreign serial-number
------- ---------- --------------------------------
DGC-1.6 true 6006016021402700787BAC217B44E411

cluster-4b::*> lun import create -vserver fli_cluster -path /vol/fli_volume/cluster_1 -foreign-disk 6006016021402700787BAC217B44E411

Error: command failed: The specified foreign disk has SCSI persistent reservations. Disk serial number: "6006016021402700787BAC217B44E411". Clear the reservation using the "storage disk remove-reservation" command before creating the import relationship.

cluster-4b::*> storage disk remove-reservation -disk DGC-1.6
cluster-4b::*> lun import create -vserver fli_cluster -path /vol/fli_volume/cluster_1 -foreign-disk 6006016021402700787BAC217B44E411
cluster-4b::*> lun online -vserver fli_cluster -path /vol/fli_volume/cluster_1
cluster-4b::*> lun import show

vserver foreign-disk path operation admin operational percent in progress state state complete
 -------------------------------------------------------------------------------
fli_cluster 6006016021402700787BAC217B44E411 /vol/fli_volume/cluster_1 import stopped stopped 0

cluster-4b::*> lun import start -vserver fli_cluster -path /vol/fli_volume/cluster_1
cluster-4b::*> lun import show

vserver foreign-disk path operation admin operational percent in progress state state complete
-------------------------------------------------------------------------------
fli_cluster 6006016021402700787BAC217B44E411 /vol/fli_volume/cluster_1 import started in_progress 7
----