---
permalink: san-migration/remove-lun-import-relationship-offline.html 
sidebar: sidebar 
keywords: fli offline, verify, migration, results 
summary: 検証ジョブはオプションですが、実行することを推奨します。ソース LUN とデスティネーション LUN が、ブロック単位で比較されます。検証ジョブには、移行とほぼ同じか、それよりも少し時間がかかります。 
---
= ONTAP FLIオフライン移行後にLUNインポート関係を削除する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
外部LUNインポート（FLI）オフライン移行が完了したら、LUNインポート関係を安全に削除できます。ホストは新しいONTAP LUNへのすべてのI/Oを新しいNetAppアレイで実行するようになり、ソースLUNは使用されなくなったため、インポート関係は不要になりました。

ONTAP9.17.1以降、FLIオフライン移行を使用した外部LUNのデータ移行は、以下の場合にサポートされますlink:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA r2 システム"^]。ASA r2システムは、ストレージ層の実装において他のONTAPシステム（ASA、 AFF、 FAS）とは異なります。ASAシステムでは、ストレージユニット（LUNまたはネームスペース）の作成時にボリュームが自動的に作成されます。各ボリュームには1つのストレージユニットのみが含まれます。そのため、 ASA r2システムでは、  `-path` LUN を作成するときにオプションではなく、ストレージ ユニット パスを含める必要があります。

.手順
. データのインポート ジョブを削除するには、インポート関係を削除します。
+
[source, cli]
----
lun import delete -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
この例では、*winvol* ボリュームと *datamig* SVM 内の *bootlun*、*fdrive*、および *gdrive* という名前の LUN のインポート関係を削除するコマンドを示します。

+
[listing]
----
DataMig-ontap::*> lun import delete -vserver datamig -path /vol/winvol/bootlun

DataMig-ontap::*> lun import delete -vserver datamig -path /vol/winvol/fdrive

DataMig-ontap::*> lun import delete -vserver datamig -path /vol/winvol/gdrive
----
. インポート ジョブが削除されたことを確認します。
+
[source, cli]
----
lun import show -vserver <SVM_name>
----
+
この例では、*datamig* SVM のインポート ジョブが削除されたことを確認するコマンドを示します。

+
[listing]
----
DataMig-ontap::*> lun import show -vserver datamig
There are no entries matching your query.
----
. 外部 LUN 属性を false に設定します
+
[source, cli]
----
storage disk modify -serial-number <serial_number> -is-foreign false
----
+
この例では、外部LUN属性をマークするコマンドを示します。  `false` *winvol* ボリュームおよび *datamig* SVM 内の *bootlun*、*fdrive*、*gdrive* という名前の LUN の場合。

+
[listing]
----
DataMig-ontap::*> storage disk modify { -serial-number 83017542001E }
-is-foreign false

DataMig-ontap::*> storage disk modify { -serial-number 83017542000E }
-is-foreign false

DataMig-ontap::*> storage disk modify { -serial-number 83017542000F }
-is-foreign false
----
. 外部LUNが次のようにマークされていることを確認します `false` 。
+
[source, cli]
----
storage disk show -array-name <array_name> -fields disk, serial-number, container-type, owner, import-in-progress, is-foreign
----
+
この例では、外部LUNが次のようにマークされていることを確認するコマンドを示します。  `false` *HITACHI_DF600F_1* アレイ上。

+
[listing]
----
DataMig-ontap::*> storage disk show -array-name HITACHI_DF600F_1 -fields disk, serial-number, container-type, owner,import-in-progress, is-foreign

disk     owner is-foreign container-type import-in-progress serial-number
-------- ----- ---------- -------------- ------------------ -------------
HIT-1.2  -     false      unassigned     false              83017542001E
HIT-1.3  -     false      unassigned     false              83017542000E
HIT-1.4  -     false      unassigned     false              83017542000F
3 entries were displayed.
----
. 宛先 LUN をオンラインにします。
+
[source, cli]
----
lun online -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
この例では、*winvol* ボリュームおよび *datamig* SVM 内の *bootlun*、*fdrive*、および *gdrive* という名前の LUN の宛先 LUN をオンラインにするコマンドを示します。

+
[listing]
----
DataMig-ontap::*> lun online -vserver datamig -path /vol/winvol/bootlun

DataMig-ontap::*> lun online -vserver datamig -path /vol/winvol/fdrive

DataMig-ontap::*> lun online -vserver datamig -path /vol/winvol/gdrive
----
. LUN がオンラインであることを確認します。
+
[source, cli]
----
lun show -vserver <SVM_name>
----
+
この例では、*datamig* SVM の LUN がオンラインであることを確認するコマンドを示します。

+
[listing]
----
DataMig-ontap::*> lun show -vserver datamig
Vserver   Path                            State   Mapped   Type        Size
--------- ------------------------------- ------- -------- -------- --------
datamig   /vol/esxvol/bootlun             online  mapped   vmware       20GB
datamig   /vol/esxvol/linuxrdmvlun        online  mapped   linux         2GB
datamig   /vol/esxvol/solrdmplun          online  mapped   solaris       2GB
3 entries were displayed.
----
. 必要に応じて、イベント ログを表示して移行結果を確認します。
+
[source, cli]
----
event log show –event fli*
----
+
この例では、FLI 移行結果のイベント ログを表示するコマンドのサンプル出力を示します。

+
[listing]
----
DataMig-ontap::*> event log  show –event fli*

7/7/2014 18:37:21   DataMig-ontap-01 INFORMATIONAL fli.lun.verify.complete: Import verify of foreign LUN 83017542001E of size 42949672960 bytes from array model DF600F belonging to vendor HITACHI  with NetApp LUN QvChd+EUXoiS is successfully completed.
7/7/2014 18:37:15   DataMig-ontap-01 INFORMATIONAL fli.lun.verify.complete: Import verify of foreign LUN 830175420015 of size 42949672960 bytes from array model DF600F belonging to vendor HITACHI  with NetApp LUN QvChd+EUXoiX is successfully completed.
7/7/2014 18:02:21   DataMig-ontap-01 INFORMATIONAL fli.lun.import.complete: Import of foreign LUN 83017542000F of size 3221225472 bytes from array model DF600F belonging to vendor HITACHI  is successfully completed. Destination NetApp LUN is QvChd+EUXoiU.
----


.次の手順
link:concept_fli_offline_post_migration_tasks.html["FLIオフライン移行の移行後タスクを実行する"] 。
