---
permalink: san-migration/task_fli_online_performing_a_disruptive_cutover.html 
sidebar: sidebar 
keywords: fli online, perform, disruptive, cutover 
summary: この例では、 FLI オンライン移行プロセスの停止を伴うカットオーバーを実行する一般的な手順を示します。 
---
= FLI オンライン：停止を伴うカットオーバーの実行
:icons: font
:imagesdir: ../media/


[role="lead"]
この例では、 FLI オンライン移行プロセスの停止を伴うカットオーバーを実行する一般的な手順を示します。

Windows 、 Linux 、 ESXi のホストの修正手順については、このガイドの後続のセクション、およびホストオペレーティングシステムとホスト接続キットのドキュメントを参照してください。

.手順
. 外部アレイで、ソース LUN がマッピングされているストレージグループを表示します。
+
該当するコマンドについては、ベンダーのドキュメントを参照してください。

. インポートする対象が ESXi ホストの LUN の場合は、 _ESXi CAW / ATS の修正トピックの手順を確認して指示に従います。
. ホストからソース LUN のマッピングを解除します。
+
[NOTE]
====
ここから中断時間が始まります。

====
+
中断は 'unmap コマンドを実行した直後に始まります通常、中断時間は分単位です。中断時間は、新しいネットアップターゲットでホストを再ポイントし、 LUN をスキャンするための時間です。

+
igroup からホスト（イニシエータ）を削除すると、その igroup にマッピングされている他の LUN に影響が及ぶため、この LUN がこの igroup にマッピングされている唯一の LUN であることを確認する必要があります。該当するコマンドについては、ベンダーのドキュメントを参照してください。

. ホストイニシエータが存在しないことを確認します。
. ONTAP クラスタで、デスティネーション LUN をオンラインにし、マッピングされていることを確認します。
+
[listing]
----
cluster::*> lun online -vserver fli -path /vol/fli_vol/OnlineFLI_LUN
----
. LUN がオンラインであることを確認します。
+
[listing]
----
cluster::*> lun show -vserver fli
Vserver   Path                            State   Mapped   Type        Size
--------- ------------------------------- ------- -------- -------- --------
fli       /vol/fli_vol/OnlineFLI_LUN      online  mapped   windows_2008  1TB
----
. ホストのディスクを再スキャンし、 ONTAP ターゲットの LUN を探して、 DSM で LUN が要求されていることを確認します。
+
[NOTE]
====
中断時間はここまでです。

====
. 想定されるすべてのパスが表示されることを確認し、イベントログでエラーがないことを確認します。
+
中断を伴うホスト修正タスク（分析フェーズと計画フェーズで特定）が残っていなければ、この移行の中断を伴う部分はこれで終了です。

+
LUN がオンラインでマッピングされた状態になり、ホストで新しい ONTAP ホスト LUN がマウントされます。読み取りは ONTAP アレイを介してソース LUN に渡され、書き込みは新しい ONTAP ホスト LUN と元のソース LUN の両方に書き込まれます。ソース LUN とデスティネーション LUN は、移行が完了して LUN 関係が解除されるまで同期されたままになります。


