---
permalink: san-migration/task_fli_offline_verifying_migration_results.html 
sidebar: sidebar 
keywords: fli offline, verify, migration, results 
summary: 検証ジョブはオプションですが、実行することを推奨します。ソース LUN とデスティネーション LUN が、ブロック単位で比較されます。検証ジョブには、移行とほぼ同じか、それよりも少し時間がかかります。 
---
= ONTAP FLIオフライン移行の結果を確認する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
LUNが外部アレイからONTAPストレージシステムに移行された後、FLIはソースLUNとターゲットLUNをブロック単位で比較し、移行が完了し、正確であることを確認します。移行検証には、移行とほぼ同じ時間（またはそれよりわずかに長い時間）かかります。

移行の検証は必須ではありませんが、強くお勧めします。

.タスク概要
ONTAP9.17.1以降、FLIオフライン移行を使用した外部LUNのデータ移行は、以下の場合にサポートされますlink:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA r2 システム"^]。ASA r2システムは、ストレージ層の実装において他のONTAPシステム（ASA、 AFF、 FAS）とは異なります。ASAシステムでは、ストレージユニット（LUNまたはネームスペース）の作成時にボリュームが自動的に作成されます。各ボリュームには1つのストレージユニットのみが含まれます。そのため、 ASA r2システムでは、  `-path` LUN を作成するときにオプションではなく、ストレージ ユニット パスを含める必要があります。

.手順
. LUN 移行の検証を開始します。
+
[source, cli]
----
lun import verify start -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
この例では、*winvol* ボリュームおよび *datamig* SVM 内の *bootlun*、*fdrive*、および *gdrive* という名前の LUN の LUN 移行検証を開始するコマンドを示します。

+
[listing]
----
DataMig-ontap::*> lun import verify start -vserver datamig -path /vol/winvol/bootlun

DataMig-ontap::*> lun import verify start -vserver datamig -path /vol/winvol/fdrive

DataMig-ontap::*> lun import verify start -vserver datamig -path /vol/winvol/gdrive
----
. 検証ステータスを監視します。
+
[source, cli]
----
lun import show -vserver <SVM_name> -fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, estimated-remaining-duration
----
+
この例では、*datamig* SVM の検証ステータスを監視するコマンドを示します。

+
[listing]
----
DataMig-ontap::*> lun import show -vserver datamig -fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, , estimated-remaining-duration

vserver foreign-disk path               admin-state operational-state percent-complete imported-blocks total-blocks estimated-remaining-duration
------- ------------ ------------------ ----------- ----------------- ---------------- --------------- ------------ ----------------------------
datamig 83017542000E /vol/winvol/fdrive started     in_progress       57               -               4194304      00:01:19
datamig 83017542000F /vol/winvol/gdrive started     in_progress       40               -               6291456      00:02:44
datamig 830175420010 /vol/linuxvol/bootlun
                                        started     in_progress       8                -               41943040     00:20:29
3 entries were displayed.
----
+
同じコマンドを実行して、検証の進行状況を追跡できます。検証ジョブが正常に完了すると、*operational-state* に *completed* というステータスが表示されます。

. LUN 検証を停止します。
+
[source, cli]
----
lun import verify stop -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
この例では、*datamig* SVM の LUN 検証を停止するコマンドを示します。

+
[listing]
----
DataMig-ontap::*> lun import verify stop -vserver datamig -path /vol/esxvol/winrdmplun
----
+
LUNをオンラインに戻す前に、LUNインポート検証を明示的に停止する必要があります。そうしないと、  `lun online`コマンドは失敗します。ステータスが検証完了と表示されていても、この手順は手動で実行する必要があります。



.次の手順
link:remove-lun-import-relationship-offline.html["LUNインポート関係を削除します"] 。
