---
permalink: san-migration/task_fli_online_verifying_migration_results.html 
sidebar: sidebar 
keywords: fli online, verify, migration, results 
summary: 検証ジョブはオプションですが、実行することを推奨します。ソース LUN とデスティネーション LUN が、ブロック単位で比較されます。検証ジョブには、移行とほぼ同じか、それよりも少し時間がかかります。 
---
= ONTAP FLIオンライン移行の結果を確認する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
LUNが外部アレイからONTAPアレイに移行された後、Foreign LUN Import（FLI）は、移行元LUNと移行先LUNをブロック単位で比較し、移行が完了し、正確であることを確認します。移行検証には、移行とほぼ同じ時間（またはそれよりわずかに長い時間）かかります。

移行の検証は必須ではありませんが、強くお勧めします。

.タスク概要
* ONTAP9.17.1以降、FLIオフライン移行を使用した外部LUNのデータ移行は、以下の場合にサポートされますlink:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA r2 システム"^]。ASA r2システムは、ストレージ層の実装において他のONTAPシステム（ASA、 AFF、 FAS）とは異なります。ASAシステムでは、ストレージユニット（LUNまたはネームスペース）の作成時にボリュームが自動的に作成されます。各ボリュームには1つのストレージユニットのみが含まれます。そのため、 ASA r2システムでは、  `-path` LUN を作成するときにオプションではなく、ストレージ ユニット パスを含める必要があります。
* 移行検証は中断を伴います。検証対象のLUNは、検証中はオフラインにする必要があります。


.手順
. 検証する LUN をオフラインにします。
+
[source, cli]
----
lun offline -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
この例では、*flivol* ボリュームおよび *fli_72C* SVM 内の *72Clun1* という名前の LUN をオフラインにするコマンドを示します。

+
[listing]
----
cluster::*> lun offline -vserver fli_72C -path /vol/flivol/72Clun1
Warning: This command will take LUN "/vol/flivol/72Clun1" in Vserver "fli_72C" offline.
Do you want to continue? {y|n}: y
----
+
ここから中断時間が始まります。

. LUN 移行の検証を開始します。
+
[source, cli]
----
lun import verify start -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
. 検証ステータスを監視します。
+
[source, cli]
----
lun import show -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
この例では、*flivol* ボリュームおよび *fli_72C* SVM 内の *72Clun1* という名前の LUN の検証ステータスを監視するコマンドを示します。

+
[listing]
----
ontaptme-fc-cluster::*> lun import show -vserver fli_72C -path /vol/flivol/72Clun1
vserver foreign-disk   path                operation admin operational percent
                                         in progress state state       complete
-------------------------------------------------------------------------------
fli_72C D0i1E+G8Wg6m   /vol/flivol/72Clun1 verify    started
                                                                        9
----
. LUN 検証を停止します。
+
[source, cli]
----
lun import verify stop -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
LUNをオンラインに復帰させる前に、lun import verifyを明示的に停止する必要があります。そうしないと、LUNのオンライン化に失敗します。ステータスに検証が完了したことが示されている場合でも、この手順は手動で実行する必要があります。

. LUN をオンラインにします。
+
[source, cli]
----
lun online -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
中断時間はここまでです。



.次の手順
link:remove-lun-import-relationship-online.html["LUNインポート関係を削除します"] 。
