---
permalink: san-migration/task_verifying_source_luns_on_destination_storage_for_offline_foreign_lun_import.html 
sidebar: sidebar 
keywords: verify, source luns, destination storage, offline fli 
summary: オフライン Foreign LUN Import プロセスの一環として、デスティネーションストレージのソース LUN を確認する必要があります。 
---
= オフライン FLI のためのデスティネーションストレージのソース LUN の確認
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
オフライン Foreign LUN Import プロセスの一環として、デスティネーションストレージのソース LUN を確認する必要があります。

.手順
. ソース LUN と、ソースストレージからデスティネーションストレージへのマッピングを確認します。
. admin ユーザを使用して SSH 経由で ONTAP ストレージにログインします。
. モードを advanced に変更します。「 set -privilege advanced 」
. 続行するかどうかを確認するメッセージが表示されたら、「 y 」と入力します。
. ONTAP でソースアレイを検出します。数分待ってから、ソースアレイの検出を再試行します。「 storage array show 」をクリックします
+
[listing]
----
DataMig-cmode::*> storage array show
Prefix                         Name   Vendor            Model Options
-------- ---------------------------- -------- ---------------- ----------
HIT-1                HITACHI_DF600F_1  HITACHI           DF600F
----
+
[NOTE]
====
ストレージアレイが初めて検出されたとき、 ONTAP の自動検出でアレイが表示されないことがあります。次の手順に従って、 ONTAP イニシエータポートが接続されているスイッチポートをリセットします。

====
. ソースアレイがすべてのイニシエータポートで検出されていることを確認します。
+
[listing]
----
DataMig-cmode::*> storage array config show -array-name HITACHI_DF600F_1
             LUN   LUN
Node         Group Count     Array Name       Array Target Port Initiator
------------ ----- ----- ---------------------------- -----------------------
DataMig-cmode-01 0     1    HITACHI_DF600F_1     50060e801046b960        0a
                                                 50060e801046b964        0b
                                                 50060e801046b968        0a
                                                 50060e801046b96c        0b
DataMig-cmode-02 0     1    HITACHI_DF600F_1     50060e801046b960        0a
                                                 50060e801046b964        0b
                                                 50060e801046b968        0a
                                                 50060e801046b96c        0b
----
. Hitachi ストレージからマッピングされているソース LUN を表示します。ディスクのプロパティとパスを確認します。
+
ケーブル配線に基づいて想定される数のパス（ソースコントローラごとに少なくとも 2 つのパス）が表示されることを確認する必要があります。また、アレイ LUN のマスキング後にイベントログを確認する必要があります。

+
[listing]
----
DataMig-cmode::*> storage disk show -array-name HITACHI_DF600F_1 -fields disk, serial-number, container-type, owner, path-lun-in-use-count, import-in-progress, is-foreign
disk     owner is-foreign container-type import-in-progress path-lun-in-use-count serial-number
-------- ----- ---------- -------------- ------------------ --------------------- -------------
HIT-1.2  -     false      unassigned     false        0,0,0,0,0,0,0,0       83017542001E
HIT-1.3  -     false      unassigned     false        0,0,0,0,0,0,0,0       83017542000E
HIT-1.14 -     false      unassigned     false        0,0,0,0,0,0,0,0       830175420019
3 entries were displayed.

DataMig-cmode::*>
----

